In [1]:
import pandas as pd
df = pd.read_json('MyData/PlaylistCreated.json')

print(df.to_string())

                     timestamp_utc            context_time  message_client_platform                     message_playlist_uri
0 2022-05-04 13:25:25.736000+00:00 2022-05-04 13:25:25.736                        0  spotify:playlist:7mEOPt6zESQjWmzknYkG7p
1 2022-05-04 13:25:05.640000+00:00 2022-05-04 13:25:05.640                        0  spotify:playlist:5zMjQ3atlPtv6UypxlxsQ4

In [2]:
df

,timestamp_utc,context_time,message_client_platform,message_playlist_uri
0,2022-05-04 13:25:25.736000+00:00,2022-05-04 13:25:25.736,0,spotify:playlist:7mEOPt6zESQjWmzknYkG7p
1,2022-05-04 13:25:05.640000+00:00,2022-05-04 13:25:05.640,0,spotify:playlist:5zMjQ3atlPtv6UypxlxsQ4

In [3]:
df2 = pd.read_json('MyData/SearchQueries.json')
df2

,platform,searchTime,searchQuery,searchInteractionURIs
0,IPHONE,2022-02-08T15:50:51.522Z[UTC],manes,[spotify:artist:0lAWpj5szCSwM4rUMHYmrr]
1,IPHONE,2022-02-08T23:24:11.674Z[UTC],upstate,[spotify:artist:5IBYZJRx7uNdYeMBYK5g8J]
2,IPHONE,2022-02-09T21:15:47.966Z[UTC],lizzo,[spotify:artist:56oDRnqbIiwx4mymNEv7dS]
3,IPHONE,2022-02-16T02:49:53.238Z[UTC],margar,[spotify:artist:13YVfXddjRIUrubItJjadb]
4,IPHONE,2022-02-19T03:05:35.044Z[UTC],visqu,[spotify:artist:1Dxmud4bSt1txVb9sZEg3H]
5,IPHONE,2022-02-19T03:06:29.468Z[UTC],mac de,[spotify:artist:3Sz7ZnJQBIHsXLUSo0OQtM]
6,IPHONE,2022-02-25T15:31:16.307Z[UTC],orvill,[spotify:artist:46auOkH1pk28rWrSoUNhLo]
7,IPHONE,2022-03-20T20:16:36.445Z[UTC],wolfcat,"[spotify:artist:7vc0GqOmqYHoUx5TAPBh53, spotif..."
8,IPHONE,2022-03-20T20:17:55.538Z[UTC],vulf,[spotify:artist:7pXu47GoqSYRajmBCjxdD6]
9,IPHONE,2022-03-31T13:07:11.513Z[UTC],bills bill,[spotify:track:1Oi2zpmL81Q0yScF1zxaC0]
10,IPHONE,2022-04-07T01:03:18.500Z[UTC],orville,[spotify:artist:46auOkH1pk28rWrSoUNhLo]
11,IPHONE,2022-04-15T13:47:48.675Z[UTC],lizzo,[spotify:artist:56oDRnqbIiwx4mymNEv7dS]
12,IPHONE,2022-04-23T15:38:07.269Z[UTC],keep it,[spotify:show:51H5r1RNYfBpvBMUgHTheq]
13,,2022-05-01T00:44:22.017Z[UTC],li,[]
14,,2022-05-01T00:44:22.149Z[UTC],li,[]
15,,2022-05-01T00:44:22.367Z[UTC],liz,[]
16,,2022-05-01T00:44:22.433Z[UTC],liz,[]
17,,2022-05-01T00:44:23.279Z[UTC],lizzo,[]
18,,2022-05-01T00:44:23.393Z[UTC],lizzo,[]

In [4]:
df3 = pd.read_json('MyData/StreamingHistory0.json')
df3

,endTime,artistName,trackName,msPlayed
0,2021-04-30 18:52,Appointment Television,Episode 292: Dream Muppet-casting and Ted Lass...,1535310
1,2021-05-04 15:25,Quakers,War Drums,149800
2,2021-05-04 15:26,Charles Mingus,Oh Lord Don't Let Them Drop That Atomic Bomb o...,4540
3,2021-05-04 15:26,Neneh Cherry,What Reason Could I Give - Kim Hiorthøy Remix,50330
4,2021-05-04 15:26,Jungle,Busy Earnin',1640
...,...,...,...,...
3068,2022-05-04 18:52,Jungle,Romeo (feat. Bas),166200
3069,2022-05-04 18:55,Jungle,Lifting You,166586
3070,2022-05-04 18:56,Jungle,Bonnie Hill,68130
3071,2022-05-04 20:50,Jungle,Bonnie Hill,1369
3072,2022-05-04 20:50,Lizzo,Soulmate,172660

In [7]:
sum(df3['msPlayed'])/60000

19367.64015